### ISSUE TITLE
won't work with the latest (v6.0.12) electron

### ISSUE THREAD

**Issue by flyisland** [electron-in-action/bookmarker#1]
Hi, I'm following the "book electron in action" in chapter 2 to create the bookmaker app, but it doesn't work. The "submit" button keeps disabled no matter what I input!

Then I clone this repo, it worked. 

But if I changed the dependency from "electron": "^1.7.10" to "^6.0.12", the issue occurs again!

**Comment by jferencak** [comment]
It looks like later versions of Electron have nodeIntegration disabled by default. When I changed main.js to have the BrowserWindow nodeIntegration set to true the example worked.

mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  });

**Comment by flyisland** [comment]
got it, thanks!
