### ISSUE TITLE
Incompatible with new Electron?

### ISSUE THREAD

**Issue by twofish0319** [electron-in-action/bookmarker#3]
I update the Electron package to ^9.0.0.
The bookmarker is not work.

**Comment by ryanorbaker** [comment]
same here.   makes the book a lot less useful when chapter one fails.

**Comment by dgreen** [comment]
See the closed issue: https://github.com/electron-in-action/bookmarker/issues/1 for the major stumbling block.

**Comment by twofish0319** [comment]
I got it.  Thank you.
